gcc: find.o ft_atoi.o main.o setdict.o
	gcc -o rush-02 find.o ft_atoi.o main.o setdict.o

find.o: find.c
	gcc -c find.c
ft_atoi.o: ft_atoi.c
	gcc -c ft_atoi.c
main.o: main.c
	gcc -c main.c
setdict.o: setdict.c
	gcc -c setdict.c
clean:
	rm -rf *.o
fclean:
	rm -rf *.o rush-02 